name: Acceptance Tests

on:
  pull_request:
    paths-ignore:
      - 'CHANGELOG.md'
      - 'CHANGELOG_PENDING.md'

jobs:
  lint:
    uses: pulumi/pulumi-yaml/.github/workflows/stage-lint.yml@main
  test:
    uses: pulumi/pulumi-yaml/.github/workflows/stage-test.yml@main
    with:
      live-test: true
