name: Pull Request Acceptance Tests

on:
  repository_dispatch:
    types: [ run-acceptance-tests-command ]

jobs:
  test:
    uses: pulumi/pulumi-yaml/.github/workflows/stage-test.yml@main
    with:
      live-test: true
      commit-ref: ${{ github.event.client_payload.pull_request.head.sha }}
    secrets:
      PULUMI_ACCESS_TOKEN:     ${{ secrets.PULUMI_ACCESS_TOKEN }}
      AWS_ACCESS_KEY_ID:       ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY:   ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_CI_ROLE_ARN:         ${{ secrets.AWS_CI_ROLE_ARN }}
