name: Publish

on:
  workflow_call:
    inputs:
      goreleaser-args:
        required: true
        type: string

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Unshallow clone for tags
        run: git fetch --prune --unshallow --tags || true
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{matrix.goversion}}
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          args: ${{ inputs.goreleaser-args }}
          version: latest
