name: simple-kubernetes
runtime: yaml
configuration:
  hostname:
    default: example.com
    type: String
variables:
  appLabels:
    app.kubernetes.io/name: nginx-demo
  servicePort: 80
resources:
  nginx-demo: # namespace name generated based on resource name
    type: kubernetes:core/v1:Namespace
  app:
    type: kubernetes:apps/v1:Deployment
    properties:
      metadata:
        namespace: ${nginx-demo.metadata.name}
      spec:
        selector:
          matchLabels: ${appLabels}
        replicas: 1
        template:
          metadata:
            labels: ${appLabels}
          spec:
            containers: [{ name: app, image: "nginx:1.15-alpine" }]
  service:
    type: kubernetes:core/v1:Service
    properties:
      metadata:
        namespace: ${nginx-demo.metadata.name}
        labels: ${appLabels}
      spec:
        type: ClusterIP
        ports: [{ port: 80, targetPort: 80, protocol: "TCP" }]
        selector: ${appLabels}
  ingress:
    type: kubernetes:networking.k8s.io/v1:Ingress
    properties:
      metadata:
        namespace: ${nginx-demo.metadata.name}
      spec:
        rules:
        - host: ${hostname}
          http:
            paths:
            - path: /
              pathType: Prefix
              backend:
                service:
                  name: ${service.metadata.name}
                  port:
                    number: 80
